version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: age
        created_at:
          days: 1
          message: 'PR needs to be at least 1 day old in order to merge'