version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'check labels if in master base branch'
    validate:
      - do: approvals
        required:
          reviewers: [ 'shineTest' ]
    fail:
      - do: checks
        state: 'in_progress'

