version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        lines:
          total:
            count: 2
          ignore_comments: true
