version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'JIRA ticket in Title'
    validate:
      - do: title
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          message: >
            Please include ticket in title in square brackets (ex: [AAA-123])
  - when: pull_request.*, pull_request_review.*
    name: 'Check Approvals'
    validate:
      - do: approvals
        required:
          reviewer: ['shine2lay']