version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "check label"
    validate:
      - do: label
        must_include:
          regex: merge-on-green

