version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: contents
        files:
          pr_diff: true
        must_exclude:
          regex: 'no_include'