version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Check Approvals'
    validate:
      - do: approvals
        max:
          count: 2
          message: 'Max is 2'
        min:
          count: 1
          message: 'Minimum is 1'
        required:
          reviewers: [ 'shineTest', 'shinelay' ]
          assignees: true
          requested_reviewers: true
          owners: true
          message: 'required approvals not met'
        block:
          changes_requested: true
          message: 'all changes requested must be resolved'
        limit:
          teams: ['@test-mergeable/reviewers']
          owners: true # boolean
  - when: pull_request.*, pull_request_review.*
    name: 'Check assignee'
    validate:
      - do: assignee
        max:
          count: 2
          message: 'Max is 2'
        min:
          count: 1
  - when: pull_request.*, pull_request_review.*
    name: 'Check baseRef'
    validate:
      - do: baseRef
        must_include:
          regex: 'base'
          message: 'PR must be against base branch'
        must_exclude:
          regex: 'head'
          message: 'head branch cannot be baseRef'
  - when: pull_request.*, pull_request_review.*
    name: 'Check changeset'
    validate:
      - do: changeset
        no_empty:
          enabled: true
          message: 'changeset cannot be empty'
        must_include:
          regex: 'base'
          message: 'PR must be against base branch'
        must_exclude:
          regex: 'head'
          message: 'head branch cannot be baseRef'
        begins_with:
          match: 'test'
          message: 'only test files are allowed to be included'
        ends_with:
          match: '.js'
          message: 'only js file are allowed for change'
        min:
          count: 1
          message: 'There must be at least one file changed'
        max:
          count: 5
          message: 'Too many file changes, please reduce them'
  - when: pull_request.*, pull_request_review.*
    name: 'Check commit'
    validate:
      - do: commit
        message:
          regex: 'TIX-'
          message: 'commit must include TIX number'
          skip_merge: true
          oldest_only: true
          single_commit_only: true
  - when: pull_request.*, pull_request_review.*
      name: 'Check contents'
      validate:
        - do: contents
          files:
            pr_diff: true
            ignore: ['.gitignore']
          must_include:
            regex: '@dev'
            message: 'all file must include documentations'
          must_exclude:
            regex: 'secret'
            message: 'Secrets are not allowed in files'
          begins_with:
            match: 'author'
            message: 'all file must start with author'
          ends_with:
            match: 'EOF'
            message: 'all file must end with keyword EOF'

