version: 2
  mergeable:
    - when: pull_request.*
      validate:
        - do: label
          and:
            - must_include:
              regex: 'qa passed'
            - must_include:
                regex: 'develop deployed'
