version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        required:
          reviewers: [ 'shineTest' ]
    fail:
      - do: checks
        state: 'in_progress'
        title: 'Awaiting Approval'

