version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: title
                must_include:
                  regex: ^(feat)(\(\w+\))?:.+$
              - do: changeset
                must_incldue:
                  regex: 'docs/changelog.rst'
                  message: 'new features needed to be added to the changelog'
          - do: title
            must_exclude:
              regex: ^(feat)(\(\w+\))?:.+$
              message: 'new features needed to be added to the changelog'

