version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          teams: ['@test-mergeable/reviewers']
          message: 'A milestone must be assigned to this pull request'