version: 2
mergeable:
  - when: pull_request.*
    name: 'merge the issue if there is a label named merge-on-green'
    validate:
      - do: label
        must_include:
          regex: 'merge-on-green'
    pass:
      - do: merge
        merge_method: 'merge'
