version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Check custom test case'
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: baseRef
                must_include:
                  regex: 'main'
              - do: labels
                and:
                  - must_include:
                      regex: 'qa passed'
                  - must_include:
                      regex: 'develop deployed'
          - do: baseRef
            must_include:
              regex: 'not main'